### ISSUE TITLE
Rename opam package to tablecloth-base

### ISSUE THREAD

**Issue by pm5** [darklang/tablecloth-ocaml-base#20]
With the new repository `tablecloth-ocaml-base` created, the old opam package name `tablecloth-native` seems a bit confusing.

I also want to explore implementing Tablecloth API with stdlib, so we might have `tablecloth-base` and `tablecloth-stdlib`.

**Comment by pbiggar** [comment]
I added you as maintainer to this and also the Tablecloth repo. Please go ahead and make changes as you see fit.

**Comment by pm5** [comment]
I renamed the package in a PR.  Also need to follow along with [this trick](https://opam.ocaml.org/doc/Tricks.html#How-to-rename-a-package) to rename the published OPAM package.

**Comment by pm5** [comment]
Published at https://github.com/ocaml/opam-repository/pull/25023
