### ISSUE TITLE
Melange support

### ISSUE THREAD

**Issue by davesnx** [darklang/tablecloth-ocaml-base#21]
Hi @pbiggar 

I want to open this issue to talk about the possibility to have tablecloth-ocaml-base to be compatible with Melange. 

The required changes are small: 
- Install melange
- Add `modes melange` into the right dune file

Melange v2 comes with the constraint of using OCaml 5.1 and dune 3.10, which I'm not entirely sure if this will be ok. Opening this to discuss what's possible and what's not. 
If this is a blocker I'm happy to have tablecloth-melange :D

Thanks!

**Comment by pbiggar** [comment]
Sure, no objections at all. As you can see there isn't really active development on tablecloth anymore, but if you find value in doing this, more than happy to provide guidance and review.

**Comment by pm5** [comment]
Hello @davesnx, I'd also love to see support on Melange.  As far as I can tell the current blockers are OCaml 5.1 and dune 3.0?  I can test tablecloth-base on OCaml 5 to see if it's ok.

**Comment by davesnx** [comment]
Yes, Melange requires dune 3.0 and OCaml 5.1, but also requires their deps to be melange also, and I believe `base` needs to be also melange compatible.

That's the real blocker here

**Comment by pm5** [comment]
It probably makes more sense to have a tablecloth-melange on top of Melange API then, I suppose?

**Comment by pm5** [comment]
It probably makes more sense to have a tablecloth-melange on top of Melange API then, I suppose?

I don't know much about Melange.  Would it be possible to save some work by adapting tablecloth-rescript to make a tablecloth-melange that's available in OPAM?

**Comment by davesnx** [comment]
Yes, a new tablecloth-melange using melange.belt would make exact sense

**Comment by pm5** [comment]
I can try migrating https://github.com/darklang/tablecloth-rescript to melange following [this guide](https://melange.re/v2.1.0/how-to-guides/#migrate-a-rescript-library-to-melange) and see how that works.

**Comment by davesnx** [comment]
That sounds perfect, let me know if you run into issues. Happy to chat in discord or here

**Comment by pm5** [comment]
https://github.com/pm5/tablecloth-melange

I'm still stuck on this error when I attempt to `dune build`:

```
File "src/TableclothComparator.re", lines 16-19, characters 4-6:
16 | ....Belt.Id.MakeComparableU({
17 |       type nonrec t = M.t;
18 |       let cmp = (. a, b) => M.compare(a, b);
19 |     }).
Error: Modules do not match:
       sig type nonrec t = M.t val cmp : t -> t -> int end
     is not included in sig type t val cmp : (t -> t -> int [@bs]) end
     Values do not match:
       val cmp : t -> t -> int
     is not included in
       val cmp : (t -> t -> int [@bs])
     The type t -> t -> int is not compatible with the type
       (t -> t -> int [@bs])
     File "src/TableclothComparator.re", line 18, characters 10-13:
       Actual declaration
```

**Comment by pm5** [comment]
Rescript syntax works though https://github.com/pm5/tablecloth-melange/tree/rescript

**Comment by davesnx** [comment]
The issue is saying that cmp is missing the `[@bs]` property which I beleive is present. Can you ensure you are using latest version of Reason from opam? I remember we changed the uncurried syntax `.` to work with melange (and not printing [@bs] anymore)

If that's not the issue, I would ensure having an interface doesn't matter.

Let me know if this helps!

**Comment by pm5** [comment]
Many thanks for the reply @davesnx.  I'm using reason 3.10.0 which is the latest version on opam.  However, it seems having an interface indeed fixed the issue.

```
$ opam list 
# Packages matching: installed
# Name                # Installed # Synopsis
base-bigarray         base
base-domains          base
base-nnp              base        Naked pointers prohibited in the OCaml heap
base-threads          base
base-unix             base
base64                3.5.1       Base64 encoding for OCaml
cmdliner              1.2.0       Declarative definition of command line interfaces for OCaml
cppo                  1.6.9       Code preprocessor like cpp for OCaml
dune                  3.12.2      Fast, portable, and opinionated build system
dune-build-info       3.12.2      Embed build information inside executable
fix                   20230505    Algorithmic building blocks for memoization, recursion, and more
melange               1.0.0       Toolchain to produce JS from Reason/OCaml
menhir                20231231    An LR(1) parser generator
menhirCST             20231231    Runtime support library for parsers generated by Menhir
menhirLib             20231231    Runtime support library for parsers generated by Menhir
menhirSdk             20231231    Compile-time library for auxiliary tools related to Menhir
merlin-extend         0.6.1       A protocol to provide custom frontend to Merlin
ocaml                 5.1.0       The OCaml compiler (virtual package)
ocaml-base-compiler   5.1.0       Official release 5.1.0
ocaml-compiler-libs   v0.12.4     OCaml compiler libraries repackaged
ocaml-config          3           OCaml Switch Configuration
ocaml-options-vanilla 1           Ensure that OCaml is compiled with no special options enabled
ocamlfind             1.9.6       A library manager for OCaml
ppx_derivers          1.2.1       Shared [@@deriving] plugin registry
ppxlib                0.31.0      Standard infrastructure for ppx rewriters
reason                3.10.0      Reason: Syntax & Toolchain for OCaml
rescript-syntax       1.0.0       ReScript syntax packaged as an opam library
sexplib0              v0.16.0     Library containing the definition of S-expressions and some base converters
stdlib-shims          0.3.0       Backport some of the new stdlib features to older compiler
```

**Comment by pm5** [comment]
Alright, I tried this version of tablecloth-melange with [melange-opam-template](https://github.com/melange-re/melange-opam-template) and it works on both the React app and the Node.js app.  Looks promising!

I moved the repository of tablecloth-melange to https://github.com/tableclothdotdev/tablecloth-melange after discussing with @pbiggar.  We can follow its progress there so I think we can close this issue.

**Comment by davesnx** [comment]
Huge @pm5

**Comment by pm5** [comment]
Just want to mention that tablecloth-melange is released [on opam](https://opam.ocaml.org/packages/tablecloth-melange/).  I'm not an expert on Reason and Melange so I think the best way to move forward is to get it out there quickly and to have more people testing it :)
