### ISSUE TITLE
Remove non-ocaml files

### ISSUE THREAD

**Issue by pbiggar** [darklang/tablecloth-ocaml-base#6]
I kicked this repo off by cloning it from the main tablecloth repo. That includes the website, documentation, rescript, and ocaml. We should remove everything from this that isn't ocaml, and move everything that is ocaml to use the repo root instead of /native.

**Comment by pbiggar** [comment]
See https://github.com/darklang/tablecloth-rescript/pull/9 for how this went in the rescript repo

**Comment by pm5** [comment]
I can do this following tablecloth-rescript.
