### ISSUE TITLE
Match rescript version

### ISSUE THREAD

**Issue by pbiggar** [darklang/tablecloth-ocaml-base#9]
The rescript version, as far as I know, is the most mature version. We should ensure we have the same functions.

**Comment by pm5** [comment]
Guess it's time for me to start tackling this :)

**Comment by pm5** [comment]
I quickly eye-balled through the definitions and it seems both have the same functions.  @pbiggar any place you can think of where there might be a mismatch?

**Comment by pbiggar** [comment]
No, that's great! I'll guess we can close this and I'll add the issues we need to be able to release this.
